SolutionWallet/Web/Pages/Account/DetailsFavoriteAccount.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web.Service;
using Web.Service.Dtos;

namespace Web.Pages.Account
{
    public class DetailsFavoriteAccountModel : PageModel
    {
        IConsultaApiWallet service;
        public Models.FavoriteAccount FavoriteAccounts { get; set; }

        public long UsuarioId { get; set; }

        public DetailsFavoriteAccountModel(IConsultaApiWallet service)
        {
            this.service = service;
        }
        public void OnGet(long ID)
        {
            UsuarioId = Convert.ToInt64(HttpContext.Session.GetString("UsuarioId"));

            this.FavoriteAccounts = GetFavoriteAccount(UsuarioId, ID);
        }

        public Models.FavoriteAccount GetFavoriteAccount(long usuarioId, long ID)
        {
            var result = new Models.FavoriteAccount();

            ResultElement<List<CuentaAsociadaDto>> res = service.GetFavoriteAccount(new Service.Param.GetFavoriteAccountsParam()
            {
                UsuarioId = usuarioId
            });

            if (res.codigo == 0)
            {
                var cuenta = res.data.Find(p => p.CuentaId == ID);

                result = new Models.FavoriteAccount()
                {
                    CuentaId = cuenta.CuentaId,
                    Alias = cuenta.Alias,
                    CuentaTipoName = cuenta.CuentaTipoName,
                    MonedaCuentaName = cuenta.MonedaCuentaName,
                    CuentaAsociadaId = cuenta.CuentaAsociadaId,
                    CuentaTipoId = cuenta.CuentaTipoId,
                    MonedaCuentaAbreb = cuenta.MonedaCuentaAbreb,
                    MonedaCuentaId = cuenta.MonedaCuentaId,
                    UsuarioId = cuenta.UsuarioId
                };


            }

            return result;
        }
    }
}

SolutionWallet/Web/Pages/Account/DetailsMyAccount.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web.Service;
using Web.Service.Dtos;

namespace Web.Pages.Account
{
    public class DetailsMyAccountModel : PageModel
    {
        IConsultaApiWallet service;
        public Models.MyAccount MyAccounts { get; set; }

        public long UsuarioId { get; set; }

        public DetailsMyAccountModel(IConsultaApiWallet service)
        {
            this.service = service;
        }
        public void OnGet(long ID)
        {
            UsuarioId = Convert.ToInt64(HttpContext.Session.GetString("UsuarioId"));

            this.MyAccounts = GetMyAccount(UsuarioId,ID);
        }
        public Models.MyAccount GetMyAccount(long usuarioId, long ID)
        {
            var result = new Models.MyAccount();

            ResultElement<List<CuentaDto>> res = service.GetMyAccounts(new Service.Param.GetMyAccountsParam()
            {
                UsuarioId = usuarioId
            });

            if (res.codigo == 0)
            {
                var  cuenta = res.data.Find(p => p.CuentaId == ID);

                result = new Models.MyAccount() 
                {
                    CuentaId = cuenta.CuentaId,
                    Balance = cuenta.Balance,
                    CuentaTipoId = cuenta.CuentaTipoId,
                    CuentaTipoName = cuenta.CuentaTipoName,
                    Estado = cuenta.Estado,
                    MonedaAbreb = cuenta.MonedaAbreb,
                    MonedaId= cuenta.MonedaId,
                    MonedaName= cuenta.MonedaName,
                    UsuarioId   = cuenta.UsuarioId
                };

               
            }

            return result;
        }
    }
}

SolutionWallet/Web/Pages/Account/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Web.Models;
using Web.Service;
using Web.Service.Dtos;

namespace Web.Pages.Account
{
    public class IndexModel : PageModel
    {
        IConsultaApiWallet service;

        public List<Models.MyAccount> MyAccounts { get; set; }
        public List<Models.FavoriteAccount> favoriteAccounts { get; set; }

        public long UsuarioId { get; set; }

        public string Mensaje { get; set; }


        public IndexModel(IConsultaApiWallet service)
        {
            this.service = service;
        }

        public void OnGet()
        {
            UsuarioId = Convert.ToInt64(HttpContext.Session.GetString("UsuarioId"));

            this.MyAccounts = GetMyAccount(UsuarioId);

            this.favoriteAccounts = GetFavoriteAccount(UsuarioId);
        }

        public List<Models.MyAccount> GetMyAccount(long usuarioId)
        {
            var result = new List<Models.MyAccount>();

            ResultElement<List<CuentaDto>> res = service.GetMyAccounts(new Service.Param.GetMyAccountsParam()
            {
                UsuarioId = usuarioId
            });

            if (res.codigo == 0) 
            {
                foreach (var cuenta in res.data)
                {
                    var myCuenta = new Models.MyAccount()
                    {   
                       CuentaId = cuenta.CuentaId,
                       Balance = cuenta.Balance,
                       CuentaTipoName = cuenta.CuentaTipoName,
                       MonedaName = cuenta.MonedaName
                    };
                    result.Add(myCuenta);
                }
            }

            return result;
        }

        public List<Models.FavoriteAccount> GetFavoriteAccount(long usuarioId) 
        {
            var result = new List<Models.FavoriteAccount>();

            ResultElement<List<CuentaAsociadaDto>> res = service.GetFavoriteAccount(new Service.Param.GetFavoriteAccountsParam()
            {
                UsuarioId = usuarioId
            });

            if (res.codigo == 0)
            {
                foreach (var cuenta in res.data)
                {
                    var cuentaFavorita = new Models.FavoriteAccount()
                    {
                        CuentaId = cuenta.CuentaId,
                        Alias = cuenta.Alias,
                        CuentaTipoName = cuenta.CuentaTipoName,
                        MonedaCuentaName = cuenta.MonedaCuentaName
                    };
                    result.Add(cuentaFavorita);
                }
            }

            return result;
        }
        public IActionResult OnGetLogout()
        {
            var res = service.CloseSession(new Service.Param.CloseSessionParam()
            {
                UsuarioId = UsuarioId
            });

            if (res.codigo == 0)
            {
                return RedirectToPage("../Index");
            }
            else
            {
                if (res.errores.Count > 0)
                {
                    var respuesta = string.Empty;
                    foreach (var msj in res.errores)
                    {
                        respuesta = respuesta + msj + ". ";
                    }
                    Mensaje = res.mensaje + " - " + respuesta;
                }

                return Page();
            }
        }
     
    }
}

SolutionWallet/Web/Pages/Account/DetailsFavoriteAccount.cshtml
@page "{ID:long}"
@model Web.Pages.Account.DetailsFavoriteAccountModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalle de Cuenta Favoritas</title>
</head>
<body>
    <h1>Detalle de Cuenta Favoritas</h1>
    <div><strong>Id Cuenta:</strong></div>
    <input asp-for="FavoriteAccounts.CuentaId" disabled />
    <div><strong>Alias:</strong></div>
    <input asp-for="FavoriteAccounts.Alias" disabled />
    <div><strong>Tipo Cuenta:</strong></div>
    <input asp-for="FavoriteAccounts.CuentaTipoName" disabled />
    <div><strong>Moneda:</strong></div>
    <input asp-for="FavoriteAccounts.MonedaCuentaName" disabled />
</body>
</html>

SolutionWallet/Web/Pages/Account/DetailsMyAccount.cshtml
@page "{ID:long}"
@model Web.Pages.Account.DetailsMyAccountModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalle de Mis Cuentas</title>
</head>
<body>
    <h1>Detalle de Mis Cuentas</h1>
    <div><strong>Id Cuenta:</strong></div>
    <input asp-for="MyAccounts.CuentaId" disabled />
    <div><strong>Balance:</strong></div>
    <input asp-for="MyAccounts.Balance" disabled />
    <div><strong>Tipo Cuenta:</strong></div>
    <input asp-for="MyAccounts.CuentaTipoName" disabled />
    <div><strong>Moneda:</strong></div>
    <input asp-for="MyAccounts.MonedaName " disabled />
</body>
</html>

SolutionWallet/Web/Pages/Account/Index.cshtml
@page 
@model Web.Pages.Account.IndexModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Historial de Cuenta</title>
</head>
<body>
    <table width="100%">
        <tr>
            <td>
                <h1>Historial de Cuenta</h1>
            </td>
            <td></td>
            <td align="right">
                <div>
                    <a asp-page="/Transaction/Index">Registrar una Transacción</a>
                </div>
            </td>
            <td align="right">
                <div>
                    <a asp-page="/ChangePassword/Index">Cambio de Contraseña</a>
                </div>
            </td>
            <td align="right">
                <div>
                    <a asp-page="Index" asp-page-handler="Logout">Cerrar Sesión</a>
                </div>
            </td>
        </tr>
    </table>
    <h3>Mi Cuenta</h3>
    <table>
        <thead>
            <tr>
                <th>Id Cuenta</th>
                <th>Balance </th>
                <th>Tipo Cuenta</th>
                <th>Moneda</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.MyAccounts)
            {
                <tr>
                    <td>@item.CuentaId</td>
                    <td>@item.Balance</td>
                    <td>@item.CuentaTipoName</td>
                    <td>@item.MonedaName</td>
                    <td>
                        <a asp-page="/Account/DetailsMyAccount" asp-route-id="@item.CuentaId">Detalle</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <br />
    <h3>Cuenta Favoritas</h3>
    <table>
        <thead>
            <tr>
                <th>Id Cuenta</th>
                <th>Alias </th>
                <th>Tipo Cuenta</th>
                <th>Moneda</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.favoriteAccounts)
            {
                <tr>
                    <td>@item.CuentaId</td>
                    <td>@item.Alias</td>
                    <td>@item.CuentaTipoName</td>
                    <td>@item.MonedaCuentaName</td>
                    <td>
                        <a asp-page="/Account/DetailsFavoriteAccount" asp-route-id="@item.CuentaId">Detalle</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        @Model.Mensaje
    </div>
</body>
</html>